// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/mock_name/user (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names=Service=UserServiceMock -package mocks -typed -destination mocks/user_service.go -self_package go.uber.org/mock/mockgen/internal/tests/mock_name/mocks go.uber.org/mock/mockgen/internal/tests/mock_name/user Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	user "go.uber.org/mock/mockgen/internal/tests/mock_name/user"
)

// UserServiceMock is a mock of Service interface.
type UserServiceMock struct {
	ctrl     *gomock.Controller
	recorder *UserServiceMockMockRecorder
	isgomock struct{}
}

// UserServiceMockMockRecorder is the mock recorder for UserServiceMock.
type UserServiceMockMockRecorder struct {
	mock *UserServiceMock
}

// NewUserServiceMock creates a new mock instance.
func NewUserServiceMock(ctrl *gomock.Controller) *UserServiceMock {
	mock := &UserServiceMock{ctrl: ctrl}
	mock.recorder = &UserServiceMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserServiceMock) EXPECT() *UserServiceMockMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *UserServiceMock) Create(name string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *UserServiceMockMockRecorder) Create(name any) *UserServiceMockCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserServiceMock)(nil).Create), name)
	return &UserServiceMockCreateCall{Call: call}
}

// UserServiceMockCreateCall wrap *gomock.Call
type UserServiceMockCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UserServiceMockCreateCall) Return(arg0 *user.User, arg1 error) *UserServiceMockCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UserServiceMockCreateCall) Do(f func(string) (*user.User, error)) *UserServiceMockCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UserServiceMockCreateCall) DoAndReturn(f func(string) (*user.User, error)) *UserServiceMockCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
