// Code generated by MockGen. DO NOT EDIT.
// Source: inorder.go
//
// Generated by this command:
//
//	mockgen -package inorder -source=inorder.go -destination=mock.go -typed
//
// Package inorder is a generated GoMock package.
package inorder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAnimal is a mock of Animal interface.
type MockAnimal struct {
	ctrl     *gomock.Controller
	recorder *MockAnimalMockRecorder
}

// MockAnimalMockRecorder is the mock recorder for MockAnimal.
type MockAnimalMockRecorder struct {
	mock *MockAnimal
}

// NewMockAnimal creates a new mock instance.
func NewMockAnimal(ctrl *gomock.Controller) *MockAnimal {
	mock := &MockAnimal{ctrl: ctrl}
	mock.recorder = &MockAnimalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimal) EXPECT() *MockAnimalMockRecorder {
	return m.recorder
}

// Feed mocks base method.
func (m *MockAnimal) Feed(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockAnimalMockRecorder) Feed(arg0 any) *AnimalFeedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockAnimal)(nil).Feed), arg0)
	return &AnimalFeedCall{Call: call}
}

// AnimalFeedCall wrap *gomock.Call
type AnimalFeedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AnimalFeedCall) Return(arg0 error) *AnimalFeedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AnimalFeedCall) Do(f func(string) error) *AnimalFeedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AnimalFeedCall) DoAndReturn(f func(string) error) *AnimalFeedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Call rewrite *gomock.Call.GetCall
func (c *AnimalFeedCall) GetCall() *gomock.Call {
	return c.Call
}

// After rewrite *gomock.Call.After
func (c *AnimalFeedCall) After(prq interface{ GetCall() *gomock.Call }) *gomock.Call {
	return c.Call.After(prq)
}

// GetNoise mocks base method.
func (m *MockAnimal) GetNoise() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoise")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNoise indicates an expected call of GetNoise.
func (mr *MockAnimalMockRecorder) GetNoise() *AnimalGetNoiseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoise", reflect.TypeOf((*MockAnimal)(nil).GetNoise))
	return &AnimalGetNoiseCall{Call: call}
}

// AnimalGetNoiseCall wrap *gomock.Call
type AnimalGetNoiseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AnimalGetNoiseCall) Return(arg0 string) *AnimalGetNoiseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AnimalGetNoiseCall) Do(f func() string) *AnimalGetNoiseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AnimalGetNoiseCall) DoAndReturn(f func() string) *AnimalGetNoiseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Call rewrite *gomock.Call.GetCall
func (c *AnimalGetNoiseCall) GetCall() *gomock.Call {
	return c.Call
}

// After rewrite *gomock.Call.After
func (c *AnimalGetNoiseCall) After(prq interface{ GetCall() *gomock.Call }) *gomock.Call {
	return c.Call.After(prq)
}
