// Code generated by MockGen. DO NOT EDIT.
// Source: bugreport.go
//
// Generated by this command:
//
//	mockgen -typed -aux_files faux=faux/faux.go -destination bugreport_mock.go -package typed -source=bugreport.go Example
//

// Package typed is a generated GoMock package.
package typed
